name: Build macOS ARM64 App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-macos-arm64:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build macOS ARM64 app
      run: npm run electron:build:mac:arm64
      env:
        # Force ARM64 build
        npm_config_target_arch: arm64
        npm_config_target_platform: darwin
        npm_config_arch: arm64
        npm_config_cache: /tmp/.npm
        npm_config_build_from_source: true
        ELECTRON_CACHE: /tmp/.electron
        ELECTRON_BUILDER_CACHE: /tmp/.electron-builder
        # macOS code signing (optional)
        CSC_IDENTITY_AUTO_DISCOVERY: false
    
    - name: Upload ARM64 artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-arm64-app-${{ github.sha }}
        path: |
          dist-electron/*arm64*.dmg
          dist-electron/*arm64*.zip
        retention-days: 30